### ISSUE TITLE
Change the inactivity day

### ISSUE THREAD

**Issue by weshockley** [oss-tooling/user-inactivity#15]
I have a customer wants to use this to remove dormant users. They want to be able to change the days to 90 days. I do not see a way to do this. The customer opened a ticket with ticket # #3198086. The customer is a large manufacture.

**Comment by garnertb** [comment]
@weshockley, apologies for the delay (and the state of this repo).  The inactivity duration is configurable via the action inputs:

```yaml
      - name: Remove Inactive Users
        id: remove-inactive
        uses: oss-tooling/user-inactivity/.github/actions/kick@v1.1.6
        with:
          org: 'avacado-corp'
          repo: user-notifications
          inactivity-duration: 30
```
